language: node_js
node_js: 6
addons:
  chrome: stable
before_script:
  - npm install
  - npm install -g selenium-webdriver
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 20
  - google-chrome-stable --headless --disable-gpu http://localhost &
  - sleep 20
script: npm run build