language: node_js
node_js: 6
addons:
  chrome: stable
before_script:
  - npm install
  - npm install -g selenium-webdriver
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
  - npm run build